package com.wuji.tv.utils

class GenreUtil {
    fun getGenre(genre: String) : String{
        var res =
        if(genre.equals("comedy",true)) "喜剧"
        else if(genre.equals("Drama",true)) "剧情"
        else if(genre.equals("children",true)) "儿童"
        else if(genre.equals("young",true)) "校园青春"
        else if(genre.equals("family ethical",true)) "家庭伦理"
        else if(genre.equals("romance",true)) "爱情"
        else if(genre.equals("sports",true)) "体育运动"
        else if(genre.equals("science fiction",true)) "科幻"
        else if(genre.equals("fantasy",true)) "奇幻"
        else if(genre.equals("disaster",true)) "灾难"
        else if(genre.equals("horror",true)) "恐怖"
        else if(genre.equals("ghost",true)) "鬼怪"
        else if(genre.equals("thriller",true)) "惊悚"
        else if(genre.equals("mystery",true)) "悬疑"
        else if(genre.equals("crime",true)) "犯罪"
        else if(genre.equals("detective",true)) "侦破警匪"
        else if(genre.equals("courtroom",true)) "庭审"
        else if(genre.equals("spy",true)) "谍战"
        else if(genre.equals("sinister gang",true)) "黑帮"
        else if(genre.equals("adventure",true)) "冒险"
        else if(genre.equals("action",true)) "动作"
        else if(genre.equals("kong fu sowordsmen",true)) "功夫武侠"
        else if(genre.equals("film noir",true)) "黑色"
        else if(genre.equals("historical",true)) "历史"
        else if(genre.equals("history",true)) "历史"
        else if(genre.equals("war",true)) "战争"
        else if(genre.equals("westerns",true)) "西部"
        else if(genre.equals("western",true)) "西部"
        else if(genre.equals("musical",true)) "音乐歌舞"
        else if(genre.equals("political",true)) "政治内幕"
        else if(genre.equals("biographical",true)) "人物传记"
        else if(genre.equals("documentary feature",true)) "纪录长片"
        else if(genre.equals("documentary short feature",true)) "纪录短片"
        else if(genre.equals("mockumentary",true)) "伪纪录"
        else if(genre.equals("animation",true)) "动画"
        else if(genre.equals("animation short",true)) "动画短片微电影"
        else if(genre.equals("adult",true)) "成人"
        else if(genre.equals("live action short",true)) "真人短片微电影"
        else if(genre.equals("teaser trailer",true)) "先导预告片"
        else if(genre.equals("official trailer",true)) "正式预告片"
        else if(genre.equals("TV spot",true)) "电视版预告片"
        else if(genre.equals("stinger",true)) "彩蛋/附加片段"
        else if(genre.equals("feature",true)) "幕后花絮"
        else if(genre.equals("serial",true)) "系列电影"
        else if(genre.equals("silent",true)) "默片"
        else if(genre.equals("MV",true)) "音乐录影"
        else if(genre.equals("telemovie",true)) "电视电影"
        else if(genre.equals("mini-series or motion picture",true)) "电视迷你剧"
        else genre
        return res
    }
}